name: Pipeline
run-name: "Build: # ${{ github.run_number }} - ${{ github.event.head_commit.message }}"
on: [push]
permissions:
  contents: write
  
jobs:
  check-changes:
    name: Check dockerfile changes
    runs-on: ubuntu-latest
    outputs:
      dockerfile_changed: ${{ steps.filter.outputs.dockerfile }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check for changes in Dockerfile
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            dockerfile:
              - 'Dockerfile'


  build-docker:
    name: Build docker image
    runs-on: ubuntu-latest
    needs: check-changes
    if: needs.check-changes.outputs.dockerfile_changed == 'true'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image with Kaniko
        uses: int128/kaniko-action@v1
        with:
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/sort_array:latest


  build-package:
    name: Build Python wheel
    runs-on: ubuntu-latest
    container: docker.io/asoteloa/sort_array:latest
    needs: [check-changes, build-docker]
    if: always()
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Preparing environment
        run: |
          cp -r /unity tests/cxx/unity
          mkdir -p build
      - name: Build CMake project
        run: |
          cd build
          cmake -G Ninja ..
      - name: Build Python wheel
        run: |
          . /venv/bin/activate
          cd build
          ninja
      - name: Test C++
        run: |
          cd build
          ctest -V
      - name: Test python
        run: |
          . /venv/bin/activate
          cd build
          pwd
          pip install $(ls ../dist/sort_array-*.whl) --force-reinstall
          python -m unittest discover -s ../tests/python -v
      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          tag_name: "0.1.0"
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

