name: Pipeline
run-name: "Build: # ${{ github.run_number }}"
on: [push]

jobs:
  check-changes:
    name: Check dockerfile changes
    runs-on: ubuntu-latest
    outputs:
      dockerfile_changed: ${{ steps.filter.outputs.dockerfile }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check for changes in Dockerfile
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            dockerfile:
              - 'Dockerfile'
  
  build-docker:
    name: Build docker image
    runs-on: ubuntu-latest
    needs: check-changes
    if: needs.check-changes.outputs.dockerfile_changed == 'true'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Building Docker image
        run: |
          echo "Building docker."
          sleep 30

  build-package:
    name: Build
    runs-on: ubuntu-latest
    needs: [check-changes, build-docker]
    if: always()
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Python package
        run: |
          echo "Building Python package"

